apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "couponmanagerbot.fullname" . }}-database-config
  labels:
    {{- include "couponmanagerbot.labels" . | nindent 4 }}
data:
  COUPON_REPO_TYPE: "{{ .Values.database.type }}"
  COUPON_REPO_CONFIG: '{{ toJson .Values.database.config }}'
