apiVersion: v1
kind: Secret
metadata:
  name: {{ include "couponmanagerbot.fullname" . }}-telegram-secret
  labels:
    {{- include "couponmanagerbot.labels" . | nindent 4 }}
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.botToken | toString | b64enc | quote }}
  ALLOWED_USER_IDS: {{ .Values.telegram.allowedUserIds | join "," | b64enc | quote }}
